#packmode speedrun
//Speed
recipes.addShapeless(<tconstruct:lumberaxe>.withTag({StatsOriginal: {AttackSpeedMultiplier: 1.0 as float, MiningSpeed: 0.0 as float, FreeModifiers: 3, Durability: 2, HarvestLevel: 0, Attack: 3.0 as float}, Unbreakable: 1 as byte, display: {LocName: "item.tinkerskyblock.axe"}, Stats: {AttackSpeedMultiplier: 1.0 as float, MiningSpeed: 0.0 as float, FreeModifiers: 0, Durability: 1, HarvestLevel: 0, Attack: 0.0 as float}, Special: {Categories: ["tool", "harvest"]}, TinkerData: {UsedModifiers: 6, Materials: ["skyblock2", "skyblock", "skyblock", "skyblock"], Modifiers: ["toolleveling", "log_breaker", "reinforced", "soulbound"]}, Modifiers: [{identifier: "skyblock", color: -3652181, level: 1}, {identifier: "toolleveling", color: 16777215, level: 1}, {identifier: "log_breaker", color: 9659178, level: 1}, {identifier: "reinforced", color: 5254787, level: 5}, {identifier: "soulbound", color: 16120748}], Traits: ["skyblock", "toolleveling", "log_breaker", "reinforced"]}),[<tconstruct:hatchet>]);

//Seeds
mods.skyresources.rockgrinder.addRecipe(<mysticalagriculture:dirt_seeds>,<minecraft:grass>);
mods.skyresources.rockgrinder.addRecipe(<mysticalagriculture:nature_seeds>,<minecraft:grass>);
mods.skyresources.rockgrinder.addRecipe(<mysticalagriculture:dye_seeds>,<minecraft:grass>);
mods.skyresources.rockgrinder.addRecipe(<mysticalagriculture:sheep_seeds>,<minecraft:grass>);
mods.skyresources.rockgrinder.addRecipe(<mysticalagriculture:cow_seeds>,<minecraft:grass>);
mods.skyresources.rockgrinder.addRecipe(<mysticalagriculture:chicken_seeds>,<minecraft:grass>);
mods.skyresources.rockgrinder.addRecipe(<mysticalagriculture:pig_seeds>,<minecraft:grass>);
mods.skyresources.rockgrinder.addRecipe(<mysticalagriculture:slime_seeds>,<minecraft:grass>);
mods.skyresources.rockgrinder.addRecipe(<mysticalagriculture:skeleton_seeds>,<minecraft:grass>);
mods.skyresources.rockgrinder.addRecipe(<mysticalagriculture:creeper_seeds>,<minecraft:grass>);
mods.skyresources.rockgrinder.addRecipe(<mysticalagriculture:spider_seeds>,<minecraft:grass>);
mods.skyresources.rockgrinder.addRecipe(<mysticalagriculture:rabbit_seeds>,<minecraft:grass>);
mods.skyresources.rockgrinder.addRecipe(<mysticalagradditions:tier6_inferium_seeds>,<minecraft:grass>);
mods.skyresources.rockgrinder.addRecipe(<mysticalagriculture:mystical_flower_seeds>,<minecraft:grass>);
mods.skyresources.rockgrinder.addRecipe(<mysticalagriculture:zombie_seeds>,<minecraft:grass>);
mods.skyresources.rockgrinder.addRecipe(<mysticalagriculture:wood_seeds>,<minecraft:grass>);
mods.skyresources.rockgrinder.addRecipe(<mysticalagriculture:stone_seeds>,<minecraft:stone>);
mods.skyresources.rockgrinder.addRecipe(<mysticalagriculture:aluminum_seeds>,<minecraft:stone>);
mods.skyresources.rockgrinder.addRecipe(<mysticalagriculture:gold_seeds>,<minecraft:stone>);
mods.skyresources.rockgrinder.addRecipe(<mysticalagriculture:tin_seeds>,<minecraft:stone>);
mods.skyresources.rockgrinder.addRecipe(<mysticalagriculture:iron_seeds>,<minecraft:stone>);
mods.skyresources.rockgrinder.addRecipe(<mysticalagriculture:uranium_seeds>,<minecraft:stone>);
mods.skyresources.rockgrinder.addRecipe(<mysticalagriculture:titanium_seeds>,<minecraft:stone>);
mods.skyresources.rockgrinder.addRecipe(<mysticalagriculture:mithril_seeds>,<minecraft:stone>);
mods.skyresources.rockgrinder.addRecipe(<mysticalagriculture:nickel_seeds>,<minecraft:stone>);
mods.skyresources.rockgrinder.addRecipe(<mysticalagriculture:lead_seeds>,<minecraft:stone>);
mods.skyresources.rockgrinder.addRecipe(<mysticalagriculture:silver_seeds>,<minecraft:stone>);
mods.skyresources.rockgrinder.addRecipe(<mysticalagriculture:copper_seeds>,<minecraft:stone>);
mods.skyresources.rockgrinder.addRecipe(<mysticalagriculture:zinc_seeds>,<minecraft:stone>);
mods.skyresources.rockgrinder.addRecipe(<mysticalagriculture:osmium_seeds>,<minecraft:stone>);
mods.skyresources.rockgrinder.addRecipe(<mysticalagriculture:iridium_seeds>,<minecraft:stone>);
mods.skyresources.rockgrinder.addRecipe(<mysticalagriculture:platinum_seeds>,<minecraft:stone>);
mods.skyresources.rockgrinder.addRecipe(<mysticalagriculture:chrome_seeds>,<minecraft:stone>);
mods.skyresources.rockgrinder.addRecipe(<mysticalagriculture:cobalt_seeds>,<minecraft:netherrack>);
mods.skyresources.rockgrinder.addRecipe(<mysticalagriculture:ardite_seeds>,<minecraft:netherrack>);
mods.skyresources.rockgrinder.addRecipe(<mysticalagriculture:wither_skeleton_seeds>,<minecraft:netherrack>);
mods.skyresources.rockgrinder.addRecipe(<mysticalagriculture:ghast_seeds>,<minecraft:netherrack>);
mods.skyresources.rockgrinder.addRecipe(<mysticalagriculture:blaze_seeds>,<minecraft:netherrack>);
mods.skyresources.rockgrinder.addRecipe(<mysticalagriculture:glowstone_seeds>,<minecraft:netherrack>);
mods.skyresources.rockgrinder.addRecipe(<mysticalagriculture:nether_seeds>,<minecraft:netherrack>);
mods.skyresources.rockgrinder.addRecipe(<mysticalagriculture:fire_seeds>,<minecraft:netherrack>);
mods.skyresources.rockgrinder.addRecipe(<mysticalagradditions:nether_star_seeds>,<minecraft:netherrack>);
mods.skyresources.rockgrinder.addRecipe(<mysticalagriculture:nether_quartz_seeds>,<minecraft:netherrack>);
mods.skyresources.rockgrinder.addRecipe(<mysticalagriculture:tungsten_seeds>,<minecraft:end_stone>);
mods.skyresources.rockgrinder.addRecipe(<mysticalagriculture:end_seeds>,<minecraft:end_stone>);
mods.skyresources.rockgrinder.addRecipe(<mysticalagriculture:enderman_seeds>,<minecraft:end_stone>);
mods.skyresources.rockgrinder.addRecipe(<mysticalagriculture:draconium_seeds>,<minecraft:end_stone>);
mods.skyresources.rockgrinder.addRecipe(<mysticalagradditions:awakened_draconium_seeds>,<minecraft:end_stone>);
mods.skyresources.rockgrinder.addRecipe(<mysticalagriculture:ender_biotite_seeds>,<minecraft:end_stone>);
mods.skyresources.rockgrinder.addRecipe(<mysticalagriculture:peridot_seeds>,<minecraft:gravel>);
mods.skyresources.rockgrinder.addRecipe(<mysticalagriculture:coal_seeds>,<minecraft:gravel>);
mods.skyresources.rockgrinder.addRecipe(<mysticalagriculture:emerald_seeds>,<minecraft:gravel>);
mods.skyresources.rockgrinder.addRecipe(<mysticalagriculture:rock_crystal_seeds>,<minecraft:gravel>);
mods.skyresources.rockgrinder.addRecipe(<mysticalagriculture:black_quartz_seeds>,<minecraft:gravel>);
mods.skyresources.rockgrinder.addRecipe(<mysticalagriculture:apatite_seeds>,<minecraft:gravel>);
mods.skyresources.rockgrinder.addRecipe(<mysticalagriculture:certus_quartz_seeds>,<minecraft:gravel>);
mods.skyresources.rockgrinder.addRecipe(<mysticalagriculture:ruby_seeds>,<minecraft:gravel>);
mods.skyresources.rockgrinder.addRecipe(<mysticalagriculture:sapphire_seeds>,<minecraft:gravel>);
mods.skyresources.rockgrinder.addRecipe(<mysticalagriculture:lapis_lazuli_seeds>,<minecraft:gravel>);
mods.skyresources.rockgrinder.addRecipe(<mysticalagriculture:diamond_seeds>,<minecraft:gravel>);
mods.skyresources.rockgrinder.addRecipe(<mysticalagriculture:saltpeter_seeds>,<minecraft:sand>);
mods.skyresources.rockgrinder.addRecipe(<mysticalagriculture:guardian_seeds>,<minecraft:sand>);
mods.skyresources.rockgrinder.addRecipe(<mysticalagriculture:aquamarine_seeds>,<minecraft:sand>);
mods.skyresources.rockgrinder.addRecipe(<mysticalagriculture:sulfur_seeds>,<minecraft:sand>);
mods.skyresources.rockgrinder.addRecipe(<mysticalagriculture:yellorium_seeds>,<minecraft:sand>);
mods.skyresources.rockgrinder.addRecipe(<mysticalagriculture:experience_seeds>,<minecraft:sand>);
mods.skyresources.rockgrinder.addRecipe(<mysticalagriculture:redstone_seeds>,<minecraft:sand>);
mods.skyresources.rockgrinder.addRecipe(<mysticalagriculture:water_seeds>,<minecraft:sand>);

//Singularities
mods.extendedcrafting.CompressionCrafting.addRecipe(<extendedcrafting:singularity:16>,<thermalfoundation:material:132>,100,<extendedcrafting:material:7>,10000);
mods.extendedcrafting.CompressionCrafting.addRecipe(<extendedcrafting:singularity:64>,<tconstruct:ingots:1>,100,<extendedcrafting:material:7>,10000);
mods.extendedcrafting.CompressionCrafting.addRecipe(<extendedcrafting:singularity:21>,<techreborn:ingot:1>,100,<extendedcrafting:material:7>,10000);
mods.extendedcrafting.CompressionCrafting.addRecipe(<extendedcrafting:singularity:19>,<thermalfoundation:material:163>,100,<extendedcrafting:material:7>,10000);
mods.extendedcrafting.CompressionCrafting.addRecipe(<extendedcrafting:singularity:33>,<techreborn:ingot:3>,100,<extendedcrafting:material:7>,10000);
mods.extendedcrafting.CompressionCrafting.addRecipe(<extendedcrafting:singularity>,<minecraft:coal>,100,<extendedcrafting:material:7>,10000);
mods.extendedcrafting.CompressionCrafting.addRecipe(<extendedcrafting:singularity:65>,<magneticraft:ingots:4>,100,<extendedcrafting:material:7>,10000);
mods.extendedcrafting.CompressionCrafting.addRecipe(<extendedcrafting:singularity:26>,<thermalfoundation:material:164>,100,<extendedcrafting:material:7>,10000);
mods.extendedcrafting.CompressionCrafting.addRecipe(<extendedcrafting:singularity:17>,<forestry:ingot_copper>,100,<extendedcrafting:material:7>,10000);
mods.extendedcrafting.CompressionCrafting.addRecipe(<extendedcrafting:singularity:6>,<minecraft:diamond>,100,<extendedcrafting:material:7>,10000);
mods.extendedcrafting.CompressionCrafting.addRecipe(<extendedcrafting:singularity:27>,<thermalfoundation:material:161>,100,<extendedcrafting:material:7>,10000);
mods.extendedcrafting.CompressionCrafting.addRecipe(<extendedcrafting:singularity:7>,<minecraft:emerald>,100,<extendedcrafting:material:7>,10000);
mods.extendedcrafting.CompressionCrafting.addRecipe(<extendedcrafting:singularity:50>,<thermalfoundation:material:167>,100,<extendedcrafting:material:7>,10000);
mods.extendedcrafting.CompressionCrafting.addRecipe(<extendedcrafting:singularity:4>,<minecraft:glowstone_dust>,100,<extendedcrafting:material:7>,10000);
mods.extendedcrafting.CompressionCrafting.addRecipe(<extendedcrafting:singularity:5>,<minecraft:gold_ingot>,100,<extendedcrafting:material:7>,10000);
mods.extendedcrafting.CompressionCrafting.addRecipe(<extendedcrafting:singularity:28>,<thermalfoundation:material:162>,100,<extendedcrafting:material:7>,10000);
mods.extendedcrafting.CompressionCrafting.addRecipe(<extendedcrafting:singularity:35>,<thermalfoundation:material:135>,100,<extendedcrafting:material:7>,10000);
mods.extendedcrafting.CompressionCrafting.addRecipe(<extendedcrafting:singularity:1>,<minecraft:iron_ingot>,100,<extendedcrafting:material:7>,10000);
mods.extendedcrafting.CompressionCrafting.addRecipe(<extendedcrafting:singularity:2>,<minecraft:dye:4>,100,<extendedcrafting:material:7>,10000);
mods.extendedcrafting.CompressionCrafting.addRecipe(<extendedcrafting:singularity:23>,<thermalfoundation:material:131>,100,<extendedcrafting:material:7>,10000);
mods.extendedcrafting.CompressionCrafting.addRecipe(<extendedcrafting:singularity:49>,<thermalfoundation:material:166>,100,<extendedcrafting:material:7>,10000);
mods.extendedcrafting.CompressionCrafting.addRecipe(<extendedcrafting:singularity:66>,<tconstruct:ingots:2>,100,<extendedcrafting:material:7>,10000);
mods.extendedcrafting.CompressionCrafting.addRecipe(<extendedcrafting:singularity:29>,<thermalfoundation:material:136>,100,<extendedcrafting:material:7>,10000);
mods.extendedcrafting.CompressionCrafting.addRecipe(<extendedcrafting:singularity:25>,<thermalfoundation:material:133>,100,<extendedcrafting:material:7>,10000);
mods.extendedcrafting.CompressionCrafting.addRecipe(<extendedcrafting:singularity:34>,<thermalfoundation:material:134>,100,<extendedcrafting:material:7>,10000);
mods.extendedcrafting.CompressionCrafting.addRecipe(<extendedcrafting:singularity:3>,<minecraft:redstone>,100,<extendedcrafting:material:7>,10000);
mods.extendedcrafting.CompressionCrafting.addRecipe(<extendedcrafting:singularity:48>,<thermalfoundation:material:165>,100,<extendedcrafting:material:7>,10000);
mods.extendedcrafting.CompressionCrafting.addRecipe(<extendedcrafting:singularity:22>,<thermalfoundation:material:130>,100,<extendedcrafting:material:7>,10000);
mods.extendedcrafting.CompressionCrafting.addRecipe(<extendedcrafting:singularity:24>,<thermalfoundation:material:160>,100,<extendedcrafting:material:7>,10000);
mods.extendedcrafting.CompressionCrafting.addRecipe(<extendedcrafting:singularity:18>,<forestry:ingot_tin>,100,<extendedcrafting:material:7>,10000);
mods.extendedcrafting.CompressionCrafting.addRecipe(<extendedcrafting:singularity:31>,<techreborn:ingot:14>,100,<extendedcrafting:material:7>,10000);
mods.extendedcrafting.CompressionCrafting.addRecipe(<extendedcrafting:singularity:30>,<magneticraft:ingots:5>,100,<extendedcrafting:material:7>,10000);
mods.extendedcrafting.CompressionCrafting.addRecipe(<extendedcrafting:singularity:32>,<immersiveengineering:metal:5>,100,<extendedcrafting:material:7>,10000);
mods.extendedcrafting.CompressionCrafting.addRecipe(<extendedcrafting:singularity:20>,<magneticraft:ingots:14>,100,<extendedcrafting:material:7>,10000);
mods.extendedcrafting.CompressionCrafting.addRecipe(<extendedcrafting:singularity_custom:68>,<bigreactors:ingotmetals>,100,<extendedcrafting:material:7>,10000);
mods.extendedcrafting.CompressionCrafting.addRecipe(<extendedcrafting:singularity_custom:69>,<plustic:alumiteingot>,100,<extendedcrafting:material:7>,10000);
mods.extendedcrafting.CompressionCrafting.addRecipe(<extendedcrafting:singularity_custom:70>,<plustic:osgloglasingot>,100,<extendedcrafting:material:7>,10000);
mods.extendedcrafting.CompressionCrafting.addRecipe(<extendedcrafting:singularity_custom:71>,<plustic:osmiridiumingot>,100,<extendedcrafting:material:7>,10000);
mods.extendedcrafting.CompressionCrafting.addRecipe(<extendedcrafting:singularity_custom:72>,<redstonearsenal:material:32>,100,<extendedcrafting:material:7>,10000);
mods.extendedcrafting.CompressionCrafting.addRecipe(<extendedcrafting:singularity_custom:73>,<techreborn:ingot:20>,100,<extendedcrafting:material:7>,10000);
mods.extendedcrafting.CompressionCrafting.addRecipe(<extendedcrafting:singularity_custom:74>,<tconstruct:ingots:5>,100,<extendedcrafting:material:7>,10000);
mods.extendedcrafting.CompressionCrafting.addRecipe(<extendedcrafting:singularity_custom:75>,<tconstruct:ingots:4>,100,<extendedcrafting:material:7>,10000);
mods.extendedcrafting.CompressionCrafting.addRecipe(<extendedcrafting:singularity_custom:76>,<tconstruct:ingots:3>,100,<extendedcrafting:material:7>,10000);
mods.extendedcrafting.CompressionCrafting.addRecipe(<extendedcrafting:singularity_custom:77>,<techreborn:ingot:17>,100,<extendedcrafting:material:7>,10000);
mods.extendedcrafting.CompressionCrafting.addRecipe(<extendedcrafting:singularity_custom:78>,<soulshardstow:materials>,100,<extendedcrafting:material:7>,10000);
mods.extendedcrafting.CompressionCrafting.addRecipe(<extendedcrafting:singularity_custom:79>,<draconicevolution:draconium_ingot>,100,<extendedcrafting:material:7>,10000);
mods.extendedcrafting.CompressionCrafting.addRecipe(<extendedcrafting:singularity_custom:80>,<draconicevolution:draconic_ingot>,100,<extendedcrafting:material:7>,10000);
mods.extendedcrafting.CompressionCrafting.addRecipe(<extendedcrafting:singularity_custom:81>,<magneticraft:ingots:11>,100,<extendedcrafting:material:7>,10000);
mods.extendedcrafting.CompressionCrafting.addRecipe(<extendedcrafting:singularity_custom:82>,<mekanism:ingot>,100,<extendedcrafting:material:7>,10000);
mods.extendedcrafting.CompressionCrafting.addRecipe(<extendedcrafting:singularity_custom:83>,<mekanism:ingot:3>,100,<extendedcrafting:material:7>,10000);
mods.extendedcrafting.CompressionCrafting.addRecipe(<extendedcrafting:singularity_custom:84>,<thermalfoundation:material:771>,100,<extendedcrafting:material:7>,10000);
mods.extendedcrafting.CompressionCrafting.addRecipe(<extendedcrafting:singularity_custom:85>,<thermalfoundation:material:772>,100,<extendedcrafting:material:7>,10000);
mods.extendedcrafting.CompressionCrafting.addRecipe(<extendedcrafting:singularity_custom:86>,<bigreactors:ingotmetals:2>,100,<extendedcrafting:material:7>,10000);
mods.extendedcrafting.CompressionCrafting.addRecipe(<extendedcrafting:singularity_custom:87>,<techreborn:part:32>,100,<extendedcrafting:material:7>,10000);
mods.extendedcrafting.CompressionCrafting.addRecipe(<extendedcrafting:singularity_custom:88>,<redstonearsenal:material:160>,100,<extendedcrafting:material:7>,10000);
mods.extendedcrafting.CompressionCrafting.addRecipe(<extendedcrafting:singularity_custom:89>,<astralsorcery:itemcraftingcomponent:1>,100,<extendedcrafting:material:7>,10000);
mods.extendedcrafting.CompressionCrafting.addRecipe(<extendedcrafting:singularity_custom:90>,<refinedstorage:quartz_enriched_iron>,100,<extendedcrafting:material:7>,10000);
mods.extendedcrafting.CompressionCrafting.addRecipe(<extendedcrafting:singularity_custom:91>,<appliedenergistics2:material>,100,<extendedcrafting:material:7>,10000);
mods.extendedcrafting.CompressionCrafting.addRecipe(<extendedcrafting:singularity_custom:92>,<appliedenergistics2:material:7>,100,<extendedcrafting:material:7>,10000);
mods.extendedcrafting.CompressionCrafting.addRecipe(<extendedcrafting:singularity_custom:93>,<forestry:apatite>,100,<extendedcrafting:material:7>,10000);
mods.extendedcrafting.CompressionCrafting.addRecipe(<extendedcrafting:singularity_custom:94>,<astralsorcery:itemcraftingcomponent>,100,<extendedcrafting:material:7>,10000);
mods.extendedcrafting.CompressionCrafting.addRecipe(<extendedcrafting:singularity_custom:95>,<techreborn:gem:2>,100,<extendedcrafting:material:7>,10000);
mods.extendedcrafting.CompressionCrafting.addRecipe(<extendedcrafting:singularity_custom:96>,<techreborn:gem>,100,<extendedcrafting:material:7>,10000);
mods.extendedcrafting.CompressionCrafting.addRecipe(<extendedcrafting:singularity_custom:97>,<techreborn:gem:1>,100,<extendedcrafting:material:7>,10000);
mods.extendedcrafting.CompressionCrafting.addRecipe(<extendedcrafting:singularity_custom:98>,<appliedenergistics2:material:5>,100,<extendedcrafting:material:7>,10000);
mods.extendedcrafting.CompressionCrafting.addRecipe(<extendedcrafting:singularity_custom:99>,<extrautils2:ingredients:12>,100,<extendedcrafting:material:7>,10000);
mods.extendedcrafting.CompressionCrafting.addRecipe(<extendedcrafting:singularity_custom:100>,<extrautils2:ingredients:17>,100,<extendedcrafting:material:7>,10000);
mods.extendedcrafting.CompressionCrafting.addRecipe(<extendedcrafting:singularity_custom:101>,<quark:biotite>,100,<extendedcrafting:material:7>,10000);
mods.extendedcrafting.CompressionCrafting.addRecipe(<extendedcrafting:singularity_custom:102>,<botania:manaresource>,100,<extendedcrafting:material:7>,10000);
mods.extendedcrafting.CompressionCrafting.addRecipe(<extendedcrafting:singularity_custom:103>,<botania:manaresource:4>,100,<extendedcrafting:material:7>,10000);
mods.extendedcrafting.CompressionCrafting.addRecipe(<extendedcrafting:singularity_custom:104>,<botania:manaresource:7>,100,<extendedcrafting:material:7>,10000);
mods.extendedcrafting.CompressionCrafting.addRecipe(<extendedcrafting:singularity_custom:105>,<plustic:mirioningot>,100,<extendedcrafting:material:7>,10000);
mods.extendedcrafting.CompressionCrafting.addRecipe(<extendedcrafting:singularity_custom:106>,<twilightforest:ironwood_ingot>,100,<extendedcrafting:material:7>,10000);
mods.extendedcrafting.CompressionCrafting.addRecipe(<extendedcrafting:singularity_custom:107>,<twilightforest:steeleaf_ingot>,100,<extendedcrafting:material:7>,10000);
mods.extendedcrafting.CompressionCrafting.addRecipe(<extendedcrafting:singularity_custom:108>,<twilightforest:fiery_ingot>,100,<extendedcrafting:material:7>,10000);
mods.extendedcrafting.CompressionCrafting.addRecipe(<extendedcrafting:singularity_custom:109>,<twilightforest:knightmetal_ingot>,100,<extendedcrafting:material:7>,10000);

//Challenge
mods.skyresources.combustion.removeRecipe(<skyresources:baseitemcomponent:3>);
mods.skyresources.combustion.addRecipe(<skyresources:baseitemcomponent:3>, [<actuallyadditions:item_crystal_empowered:3>*3,<techreborn:ingot:17>*3,<bigreactors:ingotmetals:4>*3, <environmentalmaterials:alabaster:15>*3], 2700);

recipes.remove(<mysticalagriculture:infusion_crystal>);
recipes.addShaped(<mysticalagriculture:infusion_crystal>,[
[null,<mysticalagriculture:crafting:5>],
[<mysticalagriculture:crafting:5>,<rftools:infused_diamond>,<mysticalagriculture:crafting:5>],
[null,<mysticalagriculture:crafting:5>]
]);

recipes.remove(<mysticalagriculture:master_infusion_crystal>);
recipes.addShaped(<mysticalagriculture:master_infusion_crystal>,[
[<mysticalagriculture:crafting:5>,<mysticalagradditions:awakened_draconium_essence>,<mysticalagriculture:crafting:5>],
[<mysticalagradditions:awakened_draconium_essence>,<rftools:infused_diamond>,<mysticalagradditions:awakened_draconium_essence>],
[<mysticalagriculture:crafting:5>,<mysticalagradditions:awakened_draconium_essence>,<mysticalagriculture:crafting:5>]
]);